# Generated by Django 5.0.1 on 2024-02-04 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('release_date', models.DateField(verbose_name='Release Date')),
                ('director', models.CharField(max_length=255, verbose_name='Director')),
                ('description', models.TextField(verbose_name='Description')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='movie_posters/', verbose_name='Poster')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.language', verbose_name='Language')),
            ],
        ),
    ]
